### ISSUE TITLE
dead link of n2o book

### ISSUE THREAD

**Issue by 4b5ent1** [synrc/synrc.com#3]
http://synrc.space/apps/n2o/doc/book.pdf

**Comment by 5HT** [comment]
Domain lost due to financial crysis :-)
Actually book is outdated, you need to translate new book to Chinese from https://n2o.dev ! (This is new one full stop source)
For old book use old domain `synrc.com`, http://synrc.com/apps/n2o/doc/book.pdf

Hope this helps ⭕
